// Colours and StyleSheet shared by the FoodDetail screen and its parts.
import { StyleSheet } from 'react-native';

import theme from '../../theme/mfpDark';
import scaleSize from "../../helper/scaleSize";

export const COLORS = {
    bg: theme.bg,
    text: theme.textPrimary,
    subtext: theme.textSecondary,
    hairline: theme.hairline,
    accent: theme.primary,
    accentSoft: theme.accentBlue,
    // Macro colors (match MacroTracking)
    protein: '#6c98fcff',
    carbs: '#ff7cb5ff',
    fat: '#FFC874',
};

const styles = StyleSheet.create({
    header: { minHeight: scaleSize(36), flexDirection: 'row', alignItems: 'center', paddingHorizontal: scaleSize(8) },
    headerScreenOffset: { paddingTop: scaleSize(6), paddingBottom: scaleSize(6) },
    backBtn: {
        width: scaleSize(42),
        height: scaleSize(42),
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: scaleSize(999),
    },
    headerTitle: { flex: 1, color: COLORS.text, fontFamily: 'Nunito_800ExtraBold', fontSize: scaleSize(16), textAlign: 'center' },
    saveBtn: { width: scaleSize(42), height: scaleSize(42), alignItems: 'center', justifyContent: 'center', borderRadius: scaleSize(999) },
    topSummary: { paddingHorizontal: scaleSize(18), paddingTop: scaleSize(10), paddingBottom: scaleSize(14) },
    titleRow: { flexDirection: 'row', alignItems: 'flex-start' },
    title: { flex: 1, color: COLORS.text, fontFamily: 'Nunito_800ExtraBold', fontSize: scaleSize(18), marginBottom: scaleSize(6), marginRight: scaleSize(8) },
    favoriteBtn: {
        width: scaleSize(34),
        height: scaleSize(34),
        borderRadius: scaleSize(17),
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: scaleSize(2),
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: COLORS.hairline,
        backgroundColor: 'rgba(255,255,255,0.03)',
    },
    favoriteBtnDisabled: { opacity: 0.45 },
    desc: { color: COLORS.subtext, fontFamily: 'Nunito_600SemiBold', fontSize: scaleSize(12.5) },
    hairline: { height: scaleSize(1), backgroundColor: COLORS.hairline, opacity: 0.7 },
    badgeSuffix: { color: COLORS.subtext, fontFamily: 'Outfit_700Bold', fontSize: scaleSize(12) },

    rowWrap: {
        paddingHorizontal: scaleSize(18),
        paddingVertical: scaleSize(14),
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    rowLabel: { color: COLORS.text, fontFamily: 'Nunito_700Bold', fontSize: scaleSize(14) },
    inputWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.field,
        borderRadius: scaleSize(10),
        borderWidth: scaleSize(1),
        borderColor: COLORS.hairline,
    },
    inputWrapReadOnly: { backgroundColor: theme.surface },
    input: {
        width: scaleSize(80),
        color: COLORS.text,
        fontFamily: 'Outfit_700Bold',
        fontSize: scaleSize(14),
        textAlign: 'center',
        paddingVertical: scaleSize(8),
    },
    stepBtn: { width: scaleSize(36), height: scaleSize(36), alignItems: 'center', justifyContent: 'center' },
    stepBtnDisabled: {},
    stepLeft: { borderRightWidth: 1, borderRightColor: COLORS.hairline },
    stepRight: { borderLeftWidth: 1, borderLeftColor: COLORS.hairline },
    mealChipsRow: { flexDirection: 'row', gap: scaleSize(8) },
    mealChip: {
        paddingHorizontal: scaleSize(12),
        paddingVertical: scaleSize(8),
        borderRadius: scaleSize(999),
        borderWidth: scaleSize(1),
        borderColor: COLORS.hairline,
        backgroundColor: theme.field,
    },
    mealChipReadOnly: { backgroundColor: theme.surface },
    mealChipActive: { backgroundColor: 'rgba(45,158,255,0.16)', borderColor: theme.primaryHairline },
    mealChipText: { color: COLORS.text, fontFamily: 'Outfit_700Bold', fontSize: scaleSize(12) },
    mealChipTextActive: { color: theme.primary },

    macroFourRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: scaleSize(5) },
    ringBoxFour: { alignItems: 'center', justifyContent: 'center', paddingVertical: scaleSize(4), marginRight: scaleSize(12) },
    centerLabel: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, alignItems: 'center', justifyContent: 'center' },
    centerCal: { color: COLORS.text, fontFamily: 'Outfit_800ExtraBold', fontSize: scaleSize(20) },
    centerSub: { color: COLORS.subtext, fontFamily: 'Outfit_700Bold', fontSize: scaleSize(13) },
    macroStat: { paddingVertical: scaleSize(2), paddingHorizontal: scaleSize(2), flexDirection: 'row', alignItems: 'center', gap: scaleSize(6) },
    macroStatDot: { width: scaleSize(8), height: scaleSize(8), borderRadius: scaleSize(4), marginRight: scaleSize(2) },
    macroStatLabel: { color: COLORS.subtext, fontFamily: 'Nunito_700Bold', fontSize: scaleSize(12) },
    macroStatValue: { color: COLORS.text, fontFamily: 'Outfit_800ExtraBold', fontSize: scaleSize(18) },
    sectionHeader: { paddingHorizontal: scaleSize(18), paddingVertical: scaleSize(12), flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    sectionHeaderText: { color: COLORS.subtext, fontFamily: 'Nunito_800ExtraBold', fontSize: scaleSize(13), letterSpacing: 0.3 },
    factsWrap: { paddingHorizontal: scaleSize(18), paddingVertical: scaleSize(14), gap: scaleSize(14) },
    factRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', height: scaleSize(47), paddingVertical: scaleSize(6) },
    factLabel: { color: COLORS.text, fontFamily: 'Nunito_700Bold', fontSize: scaleSize(14) },
    factValue: { color: COLORS.text, fontFamily: 'Outfit_800ExtraBold', fontSize: scaleSize(16), letterSpacing: 0.2 },
    factUnit: { color: COLORS.subtext, fontFamily: 'Outfit_700Bold', fontSize: scaleSize(12) },
    factRight: { alignItems: 'flex-end', minWidth: scaleSize(110), justifyContent: 'center' },
    factPercentSub: { color: COLORS.accentSoft, fontFamily: 'Outfit_800ExtraBold', fontSize: scaleSize(11), marginTop: scaleSize(2) },
    factPercentHigh: { color: '#F27171', fontFamily: 'Outfit_800ExtraBold', fontSize: scaleSize(11), marginTop: scaleSize(2) },
    factsEmpty: { color: COLORS.subtext, fontFamily: 'Nunito_700Bold', fontSize: scaleSize(13), paddingVertical: scaleSize(6) },
    confirmBackdrop: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: scaleSize(20),
        backgroundColor: 'rgba(0,0,0,0.58)',
    },
    confirmCard: {
        width: '94%',
        maxWidth: scaleSize(340),
        borderRadius: scaleSize(18),
        paddingVertical: scaleSize(18),
        paddingHorizontal: scaleSize(16),
        borderWidth: scaleSize(1),
        borderColor: COLORS.hairline,
        backgroundColor: theme.surface,
    },
    confirmTitle: {
        color: COLORS.text,
        fontFamily: 'Outfit_600SemiBold',
        fontSize: scaleSize(17),
        marginBottom: scaleSize(8),
    },
    confirmMessage: {
        color: COLORS.subtext,
        fontFamily: 'Nunito_700Bold',
        fontSize: scaleSize(13),
        lineHeight: scaleSize(19),
        marginBottom: scaleSize(16),
    },
    confirmActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: scaleSize(10),
    },
    confirmBtn: {
        paddingVertical: scaleSize(10),
        paddingHorizontal: scaleSize(14),
        borderRadius: scaleSize(10),
        minWidth: scaleSize(112),
        alignItems: 'center',
    },
    confirmBtnCancel: {
        backgroundColor: theme.fieldDeep,
    },
    confirmBtnDestructive: {
        backgroundColor: '#F27171',
    },
    confirmBtnText: {
        fontFamily: 'Outfit_600SemiBold',
        fontSize: scaleSize(13.5),
    },
    confirmBtnCancelText: {
        color: COLORS.text,
    },
    confirmBtnDestructiveText: {
        color: '#fff',
    },
});

export default styles;
