// Auto-generated list of exercise illustration assets.

export const exerciseImageMap = {
    '45-degree-leg-press-machine': require('../../../exercises copy/45-degree-leg-press-machine/large.png'),
    't-bar-row-machine': require('../../../exercises copy/T-bar-row-machine/large.png'),
    'ab-wheel-rollout': require('../../../exercises copy/ab-wheel-rollout/large.png'),
    'arnold-press-dumbbell': require('../../../exercises copy/arnold-press-dumbbell/large.png'),
    'around-the-world-dumbbell': require('../../../exercises copy/around-the-world-dumbbell/large.png'),
    'assisted-pull-up-band': require('../../../exercises copy/assisted-pull-up-band/large.png'),
    'back-extension': require('../../../exercises copy/back-extension/large.png'),
    'back-extension-machine': require('../../../exercises copy/back-extension-machine/large.png'),
    'back-squat-barbell': require('../../../exercises copy/back-squat-barbell/large.png'),
    'ball-slam': require('../../../exercises copy/ball-slam/large.png'),
    'bench-dip': require('../../../exercises copy/bench-dip/large.png'),
    'bench-press-barbell': require('../../../exercises copy/bench-press-barbell/large.png'),
    'bench-press-cable': require('../../../exercises copy/bench-press-cable/large.png'),
    'bench-press-dumbbell': require('../../../exercises copy/bench-press-dumbbell/large.png'),
    'bench-press-smith-machine': require('../../../exercises copy/bench-press-smith-machine/large.png'),
    'bench-split-squat': require('../../../exercises copy/bench-split-squat/large.png'),
    'bench-squat-barbell': require('../../../exercises copy/bench-squat-barbell/large.png'),
    'bent-over-row-band': require('../../../exercises copy/bent-over-row-band/large.png'),
    'bent-over-row-barbell': require('../../../exercises copy/bent-over-row-barbell/large.png'),
    'bent-over-row-dumbbell': require('../../../exercises copy/bent-over-row-dumbbell/large.png'),
    'bicep-curl-barbell': require('../../../exercises copy/bicep-curl-barbell/large.png'),
    'bicep-curl-dumbbell': require('../../../exercises copy/bicep-curl-dumbbell/large.png'),
    'bicep-curl-machine': require('../../../exercises copy/bicep-curl-machine/large.png'),
    'biceps-curl-cable': require('../../../exercises copy/biceps-curl-cable/large.png'),
    'biceps-curl-machine': require('../../../exercises copy/biceps-curl-machine/large.png'),
    'bicycle-crunch': require('../../../exercises copy/bicycle-crunch/large.png'),
    'box-jump': require('../../../exercises copy/box-jump/large.png'),
    'burpee': require('../../../exercises copy/burpee/large.png'),
    'calf-raise-dumbbell': require('../../../exercises copy/calf-raise-dumbbell/large.png'),
    'calf-raise-on-45-degree-leg-press-machine': require('../../../exercises copy/calf-raise-on-45-degree-leg-press-machine/large.png'),
    'calf-raise-on-leg-press-machine': require('../../../exercises copy/calf-raise-on-leg-press-machine/large.png'),
    'calf-raise-smith-machine': require('../../../exercises copy/calf-raise-smith-machine/large.png'),
    'chest-dip': require('../../../exercises copy/chest-dip/large.png'),
    'chest-dip-assisted': require('../../../exercises copy/chest-dip-assisted/large.png'),
    'chest-fly-cable': require('../../../exercises copy/chest-fly-cable/large.png'),
    'chest-fly-dumbbell': require('../../../exercises copy/chest-fly-dumbbell/large.png'),
    'chest-fly-machine': require('../../../exercises copy/chest-fly-machine/large.png'),
    'chest-press-machine': require('../../../exercises copy/chest-press-machine/large.png'),
    'chin-up': require('../../../exercises copy/chin-up/large.png'),
    'chin-up-assisted': require('../../../exercises copy/chin-up-assisted/large.png'),
    'clean-and-jerk-barbell': require('../../../exercises copy/clean-and-jerk-barbell/large.png'),
    'clean-high-pull-barbell': require('../../../exercises copy/clean-high-pull-barbell/large.png'),
    'close-grip-bench-press-barbell': require('../../../exercises copy/close-grip-bench-press-barbell/large.png'),
    'concentration-curl-dumbbell': require('../../../exercises copy/concentration-curl-dumbbell/large.png'),
    'cross-body-crunch': require('../../../exercises copy/cross-body-crunch/large.png'),
    'crunch': require('../../../exercises copy/crunch/large.png'),
    'crunch-cable': require('../../../exercises copy/crunch-cable/large.png'),
    'deadlift-band': require('../../../exercises copy/deadlift-band/large.png'),
    'deadlift-barbell': require('../../../exercises copy/deadlift-barbell/large.png'),
    'deadlift-dumbbell': require('../../../exercises copy/deadlift-dumbbell/large.png'),
    'deadlift-from-deficit-barbell': require('../../../exercises copy/deadlift-from-deficit-barbell/large.png'),
    'deadlift-smith-machine': require('../../../exercises copy/deadlift-smith-machine/large.png'),
    'deadlift-trap-bar': require('../../../exercises copy/deadlift-trap-bar/large.png'),
    'decline-bench-press-barbell': require('../../../exercises copy/decline-bench-press-barbell/large.png'),
    'decline-bench-press-dumbbell': require('../../../exercises copy/decline-bench-press-dumbbell/large.png'),
    'decline-bench-smith-machine': require('../../../exercises copy/decline-bench-smith-machine/large.png'),
    'decline-crunch': require('../../../exercises copy/decline-crunch/large.png'),
    'decline-sit-up': require('../../../exercises copy/decline-sit-up/large.png'),
    'floor-press-barbell': require('../../../exercises copy/floor-press-barbell/large.png'),
    'front-raise': require('../../../exercises copy/front-raise/large.png'),
    'front-raise-band': require('../../../exercises copy/front-raise-band/large.png'),
    'front-raise-barbell': require('../../../exercises copy/front-raise-barbell/large.png'),
    'front-raise-cable': require('../../../exercises copy/front-raise-cable/large.png'),
    'front-raise-dumbbell': require('../../../exercises copy/front-raise-dumbbell/large.png'),
    'glute-ham-raise': require('../../../exercises copy/glute-ham-raise/large.png'),
    'glute-kickback-machine': require('../../../exercises copy/glute-kickback-machine/large.png'),
    'goblet-squat-dumbbell': require('../../../exercises copy/goblet-squat-dumbbell/large.png'),
    'good-morning-barbell': require('../../../exercises copy/good-morning-barbell/large.png'),
    'hack-squat-sled-machine': require('../../../exercises copy/hack-squat-sled-machine/large.png'),
    'hammer-curl-band': require('../../../exercises copy/hammer-curl-band/large.png'),
    'hammer-curl-cable': require('../../../exercises copy/hammer-curl-cable/large.png'),
    'hammer-curl-dumbbell': require('../../../exercises copy/hammer-curl-dumbbell/large.png'),
    'handstand-push-up': require('../../../exercises copy/handstand-push-up/large.png'),
    'hang-clean-barbell': require('../../../exercises copy/hang-clean-barbell/large.png'),
    'hang-snatch-barbell': require('../../../exercises copy/hang-snatch-barbell/large.png'),
    'hanging-knees-to-elbows': require('../../../exercises copy/hanging-knees-to-elbows/large.png'),
    'hanging-leg-raise': require('../../../exercises copy/hanging-leg-raise/large.png'),
    'hanging-toes-to-bar': require('../../../exercises copy/hanging-toes-to-bar/large.png'),
    'hip-adduction-machine': require('../../../exercises copy/hip-adduction-machine/large.png'),
    'hip-thrust-barbell': require('../../../exercises copy/hip-thrust-barbell/large.png'),
    'incline-bench-barbell': require('../../../exercises copy/incline-bench-barbell/large.png'),
    'incline-bench-press-cable': require('../../../exercises copy/incline-bench-press-cable/large.png'),
    'incline-bench-press-dumbbell': require('../../../exercises copy/incline-bench-press-dumbbell/large.png'),
    'incline-bench-smith-machine': require('../../../exercises copy/incline-bench-smith-machine/large.png'),
    'incline-bicep-curl-dumbbell': require('../../../exercises copy/incline-bicep-curl-dumbbell/large.png'),
    'incline-chess-press-machine': require('../../../exercises copy/incline-chess-press-machine/large.png'),
    'incline-fly-dumbbell': require('../../../exercises copy/incline-fly-dumbbell/large.png'),
    'incline-row-barbell': require('../../../exercises copy/incline-row-barbell/large.png'),
    'incline-row-dumbbell': require('../../../exercises copy/incline-row-dumbbell/large.png'),
    'inverted-row': require('../../../exercises copy/inverted-row/large.png'),
    'jerk-barbell': require('../../../exercises copy/jerk-barbell/large.png'),
    'jump-shrug-barbell': require('../../../exercises copy/jump-shrug-barbell/large.png'),
    'jump-squat': require('../../../exercises copy/jump-squat/large.png'),
    'kettlebell-swing': require('../../../exercises copy/kettlebell-swing/large.png'),
    'kettlebell-turkish-get-up': require('../../../exercises copy/kettlebell-turkish-get-up/large.png'),
    'knee-push-up': require('../../../exercises copy/knee-push-up/large.png'),
    'lat-pulldown-cable': require('../../../exercises copy/lat-pulldown-cable/large.png'),
    'lat-pulldown-machine': require('../../../exercises copy/lat-pulldown-machine/large.png'),
    'lateral-raise-band': require('../../../exercises copy/lateral-raise-band/large.png'),
    'lateral-raise-cable': require('../../../exercises copy/lateral-raise-cable/large.png'),
    'lateral-raise-dumbbell': require('../../../exercises copy/lateral-raise-dumbbell/large.png'),
    'lateral-raise-machine': require('../../../exercises copy/lateral-raise-machine/large.png'),
    'leg-curl-machine': require('../../../exercises copy/leg-curl-machine/large.png'),
    'leg-extension-machine': require('../../../exercises copy/leg-extension-machine/large.png'),
    'leg-press-machine': require('../../../exercises copy/leg-press-machine/large.png'),
    'leg-raise': require('../../../exercises copy/leg-raise/large.png'),
    'leg-raise-captains-chair': require('../../../exercises copy/leg-raise-captains-chair/large.png'),
    'lunge': require('../../../exercises copy/lunge/large.png'),
    'lunge-barbell': require('../../../exercises copy/lunge-barbell/large.png'),
    'lunge-dumbbell': require('../../../exercises copy/lunge-dumbbell/large.png'),
    'lying-knee-raise': require('../../../exercises copy/lying-knee-raise/large.png'),
    'lying-leg-curl-machine': require('../../../exercises copy/lying-leg-curl-machine/large.png'),
    'muscle-up': require('../../../exercises copy/muscle-up/large.png'),
    'oblique-crunch': require('../../../exercises copy/oblique-crunch/large.png'),
    'one-arm-curl-cable': require('../../../exercises copy/one-arm-curl-cable/large.png'),
    'overhead-squat-barbell': require('../../../exercises copy/overhead-squat-barbell/large.png'),
    'overhead-tricep-extension-barbell': require('../../../exercises copy/overhead-tricep-extension-barbell/large.png'),
    'overhead-tricep-extension-cable': require('../../../exercises copy/overhead-tricep-extension-cable/large.png'),
    'pec-deck-machine': require('../../../exercises copy/pec-deck-machine/large.png'),
    'pendlay-row-barbell': require('../../../exercises copy/pendlay-row-barbell/large.png'),
    'pistol-squat': require('../../../exercises copy/pistol-squat/large.png'),
    'plank': require('../../../exercises copy/plank/large.png'),
    'power-clean': require('../../../exercises copy/power-clean/large.png'),
    'preacher-curl-barbell': require('../../../exercises copy/preacher-curl-barbell/large.png'),
    'preacher-curl-dumbbell': require('../../../exercises copy/preacher-curl-dumbbell/large.png'),
    'preacher-curl-machine': require('../../../exercises copy/preacher-curl-machine/large.png'),
    'press-under-barbell': require('../../../exercises copy/press-under-barbell/large.png'),
    'pull-through-cable': require('../../../exercises copy/pull-through-cable/large.png'),
    'pull-up': require('../../../exercises copy/pull-up/large.png'),
    'pull-up-assisted': require('../../../exercises copy/pull-up-assisted/large.png'),
    'pullover-dumbell': require('../../../exercises copy/pullover-dumbell/large.png'),
    'pullover-machine': require('../../../exercises copy/pullover-machine/large.png'),
    'push-up': require('../../../exercises copy/push-up/large.png'),
    'push-up-band': require('../../../exercises copy/push-up-band/large.png'),
    'pushdown-cable': require('../../../exercises copy/pushdown-cable/large.png'),
    'rack-pull-barbell': require('../../../exercises copy/rack-pull-barbell/large.png'),
    'raise-dumbbell': require('../../../exercises copy/raise-dumbbell/large.png'),
    'rear-fly-dumbbell': require('../../../exercises copy/rear-fly-dumbbell/large.png'),
    'reverse-concentration-curl-dumbbell': require('../../../exercises copy/reverse-concentration-curl-dumbbell/large.png'),
    'reverse-crunch': require('../../../exercises copy/reverse-crunch/large.png'),
    'reverse-curl-barbell': require('../../../exercises copy/reverse-curl-barbell/large.png'),
    'reverse-curl-dumbbell': require('../../../exercises copy/reverse-curl-dumbbell/large.png'),
    'reverse-fly-cable': require('../../../exercises copy/reverse-fly-cable/large.png'),
    'reverse-fly-dumbbell': require('../../../exercises copy/reverse-fly-dumbbell/large.png'),
    'reverse-fly-machine': require('../../../exercises copy/reverse-fly-machine/large.png'),
    'reverse-grip-bent-over-row-barbell': require('../../../exercises copy/reverse-grip-bent-over-row-barbell/large.png'),
    'reverse-plank': require('../../../exercises copy/reverse-plank/large.png'),
    'reverse-preacher-curl-barbell': require('../../../exercises copy/reverse-preacher-curl-barbell/large.png'),
    'reverse-preacher-curl-dumbbell': require('../../../exercises copy/reverse-preacher-curl-dumbbell/large.png'),
    'reverse-wrist-curl-dumbbell': require('../../../exercises copy/reverse-wrist-curl-dumbbell/large.png'),
    'romanian-deadlift-dumbbell': require('../../../exercises copy/romanian-deadlift-dumbbell/large.png'),
    'russian-twist': require('../../../exercises copy/russian-twist/large.png'),
    'seated-calf-press-machine': require('../../../exercises copy/seated-calf-press-machine/large.png'),
    'seated-calf-raise-machine': require('../../../exercises copy/seated-calf-raise-machine/large.png'),
    'seated-crunch-machine': require('../../../exercises copy/seated-crunch-machine/large.png'),
    'seated-row-cable': require('../../../exercises copy/seated-row-cable/large.png'),
    'seated-row-machine': require('../../../exercises copy/seated-row-machine/large.png'),
    'seated-shoulder-press-barbell': require('../../../exercises copy/seated-shoulder-press-barbell/large.png'),
    'seated-single-leg-press-machine': require('../../../exercises copy/seated-single-leg-press-machine/large.png'),
    'seated-wrist-curl-dumbbell': require('../../../exercises copy/seated-wrist-curl-dumbbell/large.png'),
    'shoulder-press-barbell': require('../../../exercises copy/shoulder-press-barbell/large.png'),
    'shoulder-press-cable': require('../../../exercises copy/shoulder-press-cable/large.png'),
    'shoulder-press-dumbbell': require('../../../exercises copy/shoulder-press-dumbbell/large.png'),
    'shoulder-press-machine': require('../../../exercises copy/shoulder-press-machine/large.png'),
    'shoulder-press-smith-machine': require('../../../exercises copy/shoulder-press-smith-machine/large.png'),
    'shrug-barbell': require('../../../exercises copy/shrug-barbell/large.png'),
    'shrug-dumbbell': require('../../../exercises copy/shrug-dumbbell/large.png'),
    'shrug-machine': require('../../../exercises copy/shrug-machine/large.png'),
    'shrug-smith-machine': require('../../../exercises copy/shrug-smith-machine/large.png'),
    'side-bend-cable': require('../../../exercises copy/side-bend-cable/large.png'),
    'side-bend-dumbbell': require('../../../exercises copy/side-bend-dumbbell/large.png'),
    'single-arm-lat-pulldown-cable': require('../../../exercises copy/single-arm-lat-pulldown-cable/large.png'),
    'single-arm-tricep-extension-cable': require('../../../exercises copy/single-arm-tricep-extension-cable/large.png'),
    'sit-up': require('../../../exercises copy/sit-up/large.png'),
    'skullcrusher-barbell': require('../../../exercises copy/skullcrusher-barbell/large.png'),
    'skullcrusher-dumbbell': require('../../../exercises copy/skullcrusher-dumbbell/large.png'),
    'snatch-barbell': require('../../../exercises copy/snatch-barbell/large.png'),
    'snatch-pull-barbell': require('../../../exercises copy/snatch-pull-barbell/large.png'),
    'squat': require('../../../exercises copy/squat/large.png'),
    'squat-band': require('../../../exercises copy/squat-band/large.png'),
    'squat-dumbbell': require('../../../exercises copy/squat-dumbbell/large.png'),
    'squat-machine': require('../../../exercises copy/squat-machine/large.png'),
    'squat-smith-machine': require('../../../exercises copy/squat-smith-machine/large.png'),
    'stability-ball-crunch': require('../../../exercises copy/stability-ball-crunch/large.png'),
    'standing-calf-raise-barbell': require('../../../exercises copy/standing-calf-raise-barbell/large.png'),
    'standing-calf-raise-machine': require('../../../exercises copy/standing-calf-raise-machine/large.png'),
    'standing-face-pull-cable': require('../../../exercises copy/standing-face-pull-cable/large.png'),
    'standing-preacher-curl-dumbbell': require('../../../exercises copy/standing-preacher-curl-dumbbell/large.png'),
    'standing-tricep-extention-dumbbell': require('../../../exercises copy/standing-tricep-extention-dumbbell/large.png'),
    'stiff-leg-deadlift-band': require('../../../exercises copy/stiff-leg-deadlift-band/large.png'),
    'stiff-leg-deadlift-barbell': require('../../../exercises copy/stiff-leg-deadlift-barbell/large.png'),
    'stiff-leg-deadlift-dumbbell': require('../../../exercises copy/stiff-leg-deadlift-dumbbell/large.png'),
    'sumo-deadlift-barbell': require('../../../exercises copy/sumo-deadlift-barbell/large.png'),
    'sumo-deadlift-high-pull': require('../../../exercises copy/sumo-deadlift-high-pull/large.png'),
    'thruster-barbell': require('../../../exercises copy/thruster-barbell/large.png'),
    'thruster-dumbbell': require('../../../exercises copy/thruster-dumbbell/large.png'),
    'torso-rotation-machine': require('../../../exercises copy/torso-rotation-machine/large.png'),
    'tricep-extension-machine': require('../../../exercises copy/tricep-extension-machine/large.png'),
    'twist-cable': require('../../../exercises copy/twist-cable/large.png'),
    'upright-row-barbell': require('../../../exercises copy/upright-row-barbell/large.png'),
    'upright-row-cable': require('../../../exercises copy/upright-row-cable/large.png'),
    'upright-row-dumbbell': require('../../../exercises copy/upright-row-dumbbell/large.png'),
    'v-up': require('../../../exercises copy/v-up/large.png'),
    'wide-bench-press-barbell': require('../../../exercises copy/wide-bench-press-barbell/large.png'),
    'wide-pull-up': require('../../../exercises copy/wide-pull-up/large.png'),
    'wrist-roller': require('../../../exercises copy/wrist-roller/large.png'),
    'zercher-squat-barbell': require('../../../exercises copy/zercher-squat-barbell/large.png'),
    'archer-push-up': require('../../../exercises copy/archer-push-up/large.png'),
    'band-pull-apart': require('../../../exercises copy/band-pull-apart/large.png'),
    'box-squat-barbell': require('../../../exercises copy/box-squat-barbell/large.png'),
    'bulgarian-split-squat-body-weight': require('../../../exercises copy/bulgarian-split-squat-body-weight/large.png'),
    'bulgarian-split-squat-dumbbell': require('../../../exercises copy/bulgarian-split-squat-dumbbell/large.png'),
    'cable-woodchop': require('../../../exercises copy/cable-woodchop/large.png'),
    'chest-supported-row-barbell': require('../../../exercises copy/chest-supported-row-barbell/large.png'),
    'chest-supported-row-dumbbell': require('../../../exercises copy/chest-supported-row-dumbbell/large.png'),
    'close-grip-push-up': require('../../../exercises copy/close-grip-push-up/large.png'),
    'cross-body-hammer-curl-dumbbell': require('../../../exercises copy/cross-body-hammer-curl-dumbbell/large.png'),
    'curtsy-lunge-dumbbell': require('../../../exercises copy/curtsy-lunge-dumbbell/large.png'),
    'decline-push-up': require('../../../exercises copy/decline-push-up/large.png'),
    'dragon-flag': require('../../../exercises copy/dragon-flag/large.png'),
    'dumbbell-floor-press': require('../../../exercises copy/dumbbell-floor-press/large.png'),
    'dumbbell-raise-dumbbell': require('../../../exercises copy/dumbbell-raise-dumbbell/large.png'),
    'dumbbell-squeeze-press': require('../../../exercises copy/dumbbell-squeeze-press/large.png'),
    'half-kneeling-landmine-press-barbell': require('../../../exercises copy/half-kneeling-landmine-press-barbell/large.png'),
    'hanging-windshield-wipers': require('../../../exercises copy/hanging-windshield-wipers/large.png'),
    'high-row-machine': require('../../../exercises copy/high-row-machine/large.png'),
    'hip-abduction-machine': require('../../../exercises copy/hip-abduction-machine/large.png'),
    'hip-thrust-dumbbell': require('../../../exercises copy/hip-thrust-dumbbell/large.png'),
    'hollow-hold': require('../../../exercises copy/hollow-hold/large.png'),
    'incline-hammer-curl-dumbbell': require('../../../exercises copy/incline-hammer-curl-dumbbell/large.png'),
    'incline-push-up': require('../../../exercises copy/incline-push-up/large.png'),
    'kneeling-high-to-low-cable-fly': require('../../../exercises copy/kneeling-high-to-low-cable-fly/large.png'),
    'landmine-deadlift-barbell': require('../../../exercises copy/landmine-deadlift-barbell/large.png'),
    'landmine-press-barbell': require('../../../exercises copy/landmine-press-barbell/large.png'),
    'landmine-reverse-lunge-barbell': require('../../../exercises copy/landmine-reverse-lunge-barbell/large.png'),
    'landmine-squat-barbell': require('../../../exercises copy/landmine-squat-barbell/large.png'),
    'low-to-high-cable-fly': require('../../../exercises copy/low-to-high-cable-fly/large.png'),
    'lying-cable-triceps-extension': require('../../../exercises copy/lying-cable-triceps-extension/large.png'),
    'meadows-row-barbell': require('../../../exercises copy/meadows-row-barbell/large.png'),
    'narrow-grip-seated-row-cable': require('../../../exercises copy/narrow-grip-seated-row-cable/large.png'),
    'nordic-hamstring-curl-assisted': require('../../../exercises copy/nordic-hamstring-curl-assisted/large.png'),
    'nordic-hamstring-curl-body-weight': require('../../../exercises copy/nordic-hamstring-curl-body-weight/large.png'),
    'one-leg-hip-thrust-barbell': require('../../../exercises copy/one-leg-hip-thrust-barbell/large.png'),
    'pallof-press-band': require('../../../exercises copy/pallof-press-band/large.png'),
    'pallof-press-cable': require('../../../exercises copy/pallof-press-cable/large.png'),
    'preacher-curl-cable': require('../../../exercises copy/preacher-curl-cable/large.png'),
    'rear-delt-row-dumbbell': require('../../../exercises copy/rear-delt-row-dumbbell/large.png'),
    'reverse-grip-pushdown-cable': require('../../../exercises copy/reverse-grip-pushdown-cable/large.png'),
    'reverse-hyperextension': require('../../../exercises copy/reverse-hyperextension/large.png'),
    'side-plank-hip-lift': require('../../../exercises copy/side-plank-hip-lift/large.png'),
    'single-arm-overhead-triceps-extension-dumbbell': require('../../../exercises copy/single-arm-overhead-triceps-extension-dumbbell/large.png'),
    'single-arm-standing-row-cable': require('../../../exercises copy/single-arm-standing-row-cable/large.png'),
    'sissy-squat-body-weight': require('../../../exercises copy/sissy-squat-body-weight/large.png'),
    'spider-curl-dumbbell': require('../../../exercises copy/spider-curl-dumbbell/large.png'),
    'standing-cable-crunch': require('../../../exercises copy/standing-cable-crunch/large.png'),
    'step-up-barbell': require('../../../exercises copy/step-up-barbell/large.png'),
    'step-up-dumbbell': require('../../../exercises copy/step-up-dumbbell/large.png'),
    'tate-press-dumbbell': require('../../../exercises copy/tate-press-dumbbell/large.png'),
    'tricep-kickback-cable': require('../../../exercises copy/tricep-kickback-cable/large.png'),
    'tricep-kickback-dumbbell': require('../../../exercises copy/tricep-kickback-dumbbell/large.png'),
    'wide-grip-seated-row-cable': require('../../../exercises copy/wide-grip-seated-row-cable/large.png'),
    'y-raise-dumbbell': require('../../../exercises copy/y-raise-dumbbell/large.png'),
    'z-press-barbell': require('../../../exercises copy/z-press-barbell/large.png'),
};


const EXERCISE_SLUG_OVERRIDES = {
    "bicep-curl-machine": "biceps-curl-machine",
    "incline-chest-press-machine": "incline-chess-press-machine",
    "pullover-dumbbell": "pullover-dumbell",
    "standing-tricep-extension-dumbbell": "standing-tricep-extention-dumbbell",
};

const normalizeName = (rawName) => {
    if (typeof rawName !== "string") return "";
    return rawName
        .toLowerCase()
        .replace(/&/g, " and ")
        .replace(/[’']/g, "")
        .replace(/\(([^)]+)\)/g, " $1 ")
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/-+/g, "-")
        .replace(/^-|-$/g, "");
};

export const toExerciseSlug = (name) => {
    const normalized = normalizeName(name);
    if (!normalized) return "";
    return EXERCISE_SLUG_OVERRIDES[normalized] || normalized;
};

export const getExerciseImageSource = (slug) => exerciseImageMap[slug] || null;

export const resolveExerciseImageByName = (name) =>
    getExerciseImageSource(toExerciseSlug(name));
