export const exercises = [
    { name: '45-Degree Leg Press (Machine)', muscleGroup: 'Legs', equipment: 'Machine' },
    { name: 'T-Bar Row (Machine)', muscleGroup: 'Back', equipment: 'Machine' },
    { name: 'Ab Wheel Rollout', muscleGroup: 'Abs', equipment: 'Ab Wheel' },
    { name: 'Arnold Press (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
    { name: 'Around the World (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
    { name: 'Assisted Pull-Up (Band)', muscleGroup: 'Back', equipment: 'Band' },
    { name: 'Back Extension', muscleGroup: 'Back', equipment: 'Body Weight' },
    { name: 'Back Extension (Machine)', muscleGroup: 'Back', equipment: 'Machine' },
    { name: 'Back Squat (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell' },
    { name: 'Ball Slam', muscleGroup: 'Abs', equipment: 'Medicine Ball' },
    { name: 'Bench Dip', muscleGroup: 'Arms', equipment: 'Body Weight' },
    { name: 'Bench Press (Barbell)', muscleGroup: 'Chest', equipment: 'Barbell' },
    { name: 'Bench Press (Cable)', muscleGroup: 'Chest', equipment: 'Cable' },
    { name: 'Bench Press (Dumbbell)', muscleGroup: 'Chest', equipment: 'Dumbbell' },
    { name: 'Bench Press (Smith Machine)', muscleGroup: 'Chest', equipment: 'Smith Machine' },
    { name: 'Bench Split Squat', muscleGroup: 'Legs', equipment: 'Body Weight' },
    { name: 'Bench Squat (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell' },
    { name: 'Bent-Over Row (Band)', muscleGroup: 'Back', equipment: 'Band' },
    { name: 'Bent-Over Row (Barbell)', muscleGroup: 'Back', equipment: 'Barbell' },
    { name: 'Bent-Over Row (Dumbbell)', muscleGroup: 'Back', equipment: 'Dumbbell' },
    { name: 'Bicep Curl (Barbell)', muscleGroup: 'Arms', equipment: 'Barbell' },
    { name: 'Bicep Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell' },
    { name: 'Bicep Curl (Machine)', muscleGroup: 'Arms', equipment: 'Machine' },
    { name: 'Biceps Curl (Cable)', muscleGroup: 'Arms', equipment: 'Cable' },
    { name: 'Bicycle Crunch', muscleGroup: 'Abs', equipment: 'Body Weight' },
    { name: 'Box Jump', muscleGroup: 'Legs', equipment: 'Plyo Box' },
    { name: 'Burpee', muscleGroup: 'Full Body', equipment: 'Body Weight' },
    { name: 'Calf Raise (Dumbbell)', muscleGroup: 'Legs', equipment: 'Dumbbell' },
    { name: 'Calf Raise on 45-Degree Leg Press (Machine)', muscleGroup: 'Legs', equipment: 'Machine' },
    { name: 'Calf Raise on Leg Press (Machine)', muscleGroup: 'Legs', equipment: 'Machine' },
    { name: 'Calf Raise (Smith Machine)', muscleGroup: 'Legs', equipment: 'Smith Machine' },
    { name: 'Chest Dip', muscleGroup: 'Chest', equipment: 'Body Weight' },
    { name: 'Chest Dip (Assisted)', muscleGroup: 'Chest', equipment: 'Machine' },
    { name: 'Chest Fly (Cable)', muscleGroup: 'Chest', equipment: 'Cable' },
    { name: 'Chest Fly (Dumbbell)', muscleGroup: 'Chest', equipment: 'Dumbbell' },
    { name: 'Chest Fly (Machine)', muscleGroup: 'Chest', equipment: 'Machine' },
    { name: 'Chest Press (Machine)', muscleGroup: 'Chest', equipment: 'Machine' },
    { name: 'Chin-Up', muscleGroup: 'Back', equipment: 'Body Weight' },
    { name: 'Chin-Up (Assisted)', muscleGroup: 'Back', equipment: 'Machine' },
    { name: 'Clean and Jerk (Barbell)', muscleGroup: 'Full Body', equipment: 'Barbell' },
    { name: 'Clean High Pull (Barbell)', muscleGroup: 'Back', equipment: 'Barbell' },
    { name: 'Close-Grip Bench Press (Barbell)', muscleGroup: 'Arms', equipment: 'Barbell' },
    { name: 'Concentration Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell' },
    { name: 'Cross-Body Crunch', muscleGroup: 'Abs', equipment: 'Body Weight' },
    { name: 'Crunch', muscleGroup: 'Abs', equipment: 'Body Weight' },
    { name: 'Crunch (Cable)', muscleGroup: 'Abs', equipment: 'Cable' },
    { name: 'Deadlift (Band)', muscleGroup: 'Legs', equipment: 'Band' },
    { name: 'Deadlift (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell' },
    { name: 'Deadlift (Dumbbell)', muscleGroup: 'Legs', equipment: 'Dumbbell' },
    { name: 'Deadlift from Deficit (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell' },
    { name: 'Deadlift (Smith Machine)', muscleGroup: 'Legs', equipment: 'Smith Machine' },
    { name: 'Deadlift (Trap Bar)', muscleGroup: 'Legs', equipment: 'Trap Bar' },
    { name: 'Decline Bench Press (Barbell)', muscleGroup: 'Chest', equipment: 'Barbell' },
    { name: 'Decline Bench Press (Dumbbell)', muscleGroup: 'Chest', equipment: 'Dumbbell' },
    { name: 'Decline Bench (Smith Machine)', muscleGroup: 'Chest', equipment: 'Smith Machine' },
    { name: 'Decline Crunch', muscleGroup: 'Abs', equipment: 'Body Weight' },
    { name: 'Decline Sit-Up', muscleGroup: 'Abs', equipment: 'Body Weight' },
    { name: 'Floor Press (Barbell)', muscleGroup: 'Chest', equipment: 'Barbell' },
    { name: 'Front Raise', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
    { name: 'Front Raise (Band)', muscleGroup: 'Shoulders', equipment: 'Band' },
    { name: 'Front Raise (Barbell)', muscleGroup: 'Shoulders', equipment: 'Barbell' },
    { name: 'Front Raise (Cable)', muscleGroup: 'Shoulders', equipment: 'Cable' },
    { name: 'Front Raise (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
    { name: 'Glute-Ham Raise', muscleGroup: 'Legs', equipment: 'GHD' },
    { name: 'Glute Kickback (Machine)', muscleGroup: 'Legs', equipment: 'Machine' },
    { name: 'Goblet Squat (Dumbbell)', muscleGroup: 'Legs', equipment: 'Dumbbell' },
    { name: 'Good Morning (Barbell)', muscleGroup: 'Back', equipment: 'Barbell' },
    { name: 'Hack Squat (Sled Machine)', muscleGroup: 'Legs', equipment: 'Sled Machine' },
    { name: 'Hammer Curl (Band)', muscleGroup: 'Arms', equipment: 'Band' },
    { name: 'Hammer Curl (Cable)', muscleGroup: 'Arms', equipment: 'Cable' },
    { name: 'Hammer Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell' },
    { name: 'Handstand Push-Up', muscleGroup: 'Shoulders', equipment: 'Body Weight' },
    { name: 'Hang Clean (Barbell)', muscleGroup: 'Full Body', equipment: 'Barbell' },
    { name: 'Hang Snatch (Barbell)', muscleGroup: 'Full Body', equipment: 'Barbell' },
    { name: 'Hanging Knees to Elbows', muscleGroup: 'Abs', equipment: 'Body Weight' },
    { name: 'Hanging Leg Raise', muscleGroup: 'Abs', equipment: 'Body Weight' },
    { name: 'Hanging Toes to Bar', muscleGroup: 'Abs', equipment: 'Body Weight' },
    { name: 'Hip Adduction (Machine)', muscleGroup: 'Legs', equipment: 'Machine' },
    { name: 'Hip Thrust (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell' },
    { name: 'Incline Bench (Barbell)', muscleGroup: 'Chest', equipment: 'Barbell' },
    { name: 'Incline Bench Press (Cable)', muscleGroup: 'Chest', equipment: 'Cable' },
    { name: 'Incline Bench Press (Dumbbell)', muscleGroup: 'Chest', equipment: 'Dumbbell' },
    { name: 'Incline Bench (Smith Machine)', muscleGroup: 'Chest', equipment: 'Smith Machine' },
    { name: 'Incline Bicep Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell' },
    { name: 'Incline Chest Press (Machine)', muscleGroup: 'Chest', equipment: 'Machine' },
    { name: 'Incline Fly (Dumbbell)', muscleGroup: 'Chest', equipment: 'Dumbbell' },
    { name: 'Incline Row (Barbell)', muscleGroup: 'Back', equipment: 'Barbell' },
    { name: 'Incline Row (Dumbbell)', muscleGroup: 'Back', equipment: 'Dumbbell' },
    { name: 'Inverted Row', muscleGroup: 'Back', equipment: 'Body Weight' },
    { name: 'Jerk (Barbell)', muscleGroup: 'Full Body', equipment: 'Barbell' },
    { name: 'Jump Shrug (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell' },
    { name: 'Jump Squat', muscleGroup: 'Legs', equipment: 'Body Weight' },
    { name: 'Kettlebell Swing', muscleGroup: 'Full Body', equipment: 'Kettlebell' },
    { name: 'Kettlebell Turkish Get-Up', muscleGroup: 'Full Body', equipment: 'Kettlebell' },
    { name: 'Knee Push-Up', muscleGroup: 'Chest', equipment: 'Body Weight' },
    { name: 'Lat Pulldown (Cable)', muscleGroup: 'Back', equipment: 'Cable' },
    { name: 'Lat Pulldown (Machine)', muscleGroup: 'Back', equipment: 'Machine' },
    { name: 'Lateral Raise (Band)', muscleGroup: 'Shoulders', equipment: 'Band' },
    { name: 'Lateral Raise (Cable)', muscleGroup: 'Shoulders', equipment: 'Cable' },
    { name: 'Lateral Raise (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
    { name: 'Lateral Raise (Machine)', muscleGroup: 'Shoulders', equipment: 'Machine' },
    { name: 'Leg Curl (Machine)', muscleGroup: 'Legs', equipment: 'Machine' },
    { name: 'Leg Extension (Machine)', muscleGroup: 'Legs', equipment: 'Machine' },
    { name: 'Leg Press (Machine)', muscleGroup: 'Legs', equipment: 'Machine' },
    { name: 'Leg Raise', muscleGroup: 'Abs', equipment: 'Body Weight' },
    { name: 'Leg Raise (Captain\'s Chair)', muscleGroup: 'Abs', equipment: 'Captain\'s Chair' },
    { name: 'Lunge', muscleGroup: 'Legs', equipment: 'Body Weight' },
    { name: 'Lunge (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell' },
    { name: 'Lunge (Dumbbell)', muscleGroup: 'Legs', equipment: 'Dumbbell' },
    { name: 'Lying Knee Raise', muscleGroup: 'Abs', equipment: 'Body Weight' },
    { name: 'Lying Leg Curl (Machine)', muscleGroup: 'Legs', equipment: 'Machine' },
    { name: 'Muscle-Up', muscleGroup: 'Full Body', equipment: 'Body Weight' },
    { name: 'Oblique Crunch', muscleGroup: 'Abs', equipment: 'Body Weight' },
    { name: 'One-Arm Curl (Cable)', muscleGroup: 'Arms', equipment: 'Cable' },
    { name: 'Overhead Squat (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell' },
    { name: 'Overhead Tricep Extension (Barbell)', muscleGroup: 'Arms', equipment: 'Barbell' },
    { name: 'Overhead Tricep Extension (Cable)', muscleGroup: 'Arms', equipment: 'Cable' },
    { name: 'Pec Deck (Machine)', muscleGroup: 'Chest', equipment: 'Machine' },
    { name: 'Pendlay Row (Barbell)', muscleGroup: 'Back', equipment: 'Barbell' },
    { name: 'Pistol Squat', muscleGroup: 'Legs', equipment: 'Body Weight' },
    { name: 'Plank', muscleGroup: 'Abs', equipment: 'Body Weight' },
    { name: 'Power Clean', muscleGroup: 'Full Body', equipment: 'Barbell' },
    { name: 'Preacher Curl (Barbell)', muscleGroup: 'Arms', equipment: 'Barbell' },
    { name: 'Preacher Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell' },
    { name: 'Preacher Curl (Machine)', muscleGroup: 'Arms', equipment: 'Machine' },
    { name: 'Press Under (Barbell)', muscleGroup: 'Shoulders', equipment: 'Barbell' },
    { name: 'Pull-Through (Cable)', muscleGroup: 'Back', equipment: 'Cable' },
    { name: 'Pull-Up', muscleGroup: 'Back', equipment: 'Body Weight' },
    { name: 'Pull-Up (Assisted)', muscleGroup: 'Back', equipment: 'Machine' },
    { name: 'Pullover (Dumbbell)', muscleGroup: 'Chest', equipment: 'Dumbbell' },
    { name: 'Pullover (Machine)', muscleGroup: 'Chest', equipment: 'Machine' },
    { name: 'Push-Up', muscleGroup: 'Chest', equipment: 'Body Weight' },
    { name: 'Push-Up (Band)', muscleGroup: 'Chest', equipment: 'Band' },
    { name: 'Pushdown (Cable)', muscleGroup: 'Arms', equipment: 'Cable' },
    { name: 'Rack Pull (Barbell)', muscleGroup: 'Back', equipment: 'Barbell' },
    { name: 'Raise (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
    { name: 'Rear Fly (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
    { name: 'Reverse Concentration Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell' },
    { name: 'Reverse Crunch', muscleGroup: 'Abs', equipment: 'Body Weight' },
    { name: 'Reverse Curl (Barbell)', muscleGroup: 'Arms', equipment: 'Barbell' },
    { name: 'Reverse Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell' },
    { name: 'Reverse Fly (Cable)', muscleGroup: 'Shoulders', equipment: 'Cable' },
    { name: 'Reverse Fly (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
    { name: 'Reverse Fly (Machine)', muscleGroup: 'Shoulders', equipment: 'Machine' },
    { name: 'Reverse Grip Bent-Over Row (Barbell)', muscleGroup: 'Back', equipment: 'Barbell' },
    { name: 'Reverse Plank', muscleGroup: 'Abs', equipment: 'Body Weight' },
    { name: 'Reverse Preacher Curl (Barbell)', muscleGroup: 'Arms', equipment: 'Barbell' },
    { name: 'Reverse Preacher Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell' },
    { name: 'Reverse Wrist Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell' },
    { name: 'Romanian Deadlift (Dumbbell)', muscleGroup: 'Legs', equipment: 'Dumbbell' },
    { name: 'Russian Twist', muscleGroup: 'Abs', equipment: 'Body Weight' },
    { name: 'Seated Calf Press (Machine)', muscleGroup: 'Legs', equipment: 'Machine' },
    { name: 'Seated Calf Raise (Machine)', muscleGroup: 'Legs', equipment: 'Machine' },
    { name: 'Seated Crunch (Machine)', muscleGroup: 'Abs', equipment: 'Machine' },
    { name: 'Seated Row (Cable)', muscleGroup: 'Back', equipment: 'Cable' },
    { name: 'Seated Row (Machine)', muscleGroup: 'Back', equipment: 'Machine' },
    { name: 'Seated Shoulder Press (Barbell)', muscleGroup: 'Shoulders', equipment: 'Barbell' },
    { name: 'Seated Single Leg Press (Machine)', muscleGroup: 'Legs', equipment: 'Machine' },
    { name: 'Seated Wrist Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell' },
    { name: 'Shoulder Press (Barbell)', muscleGroup: 'Shoulders', equipment: 'Barbell' },
    { name: 'Shoulder Press (Cable)', muscleGroup: 'Shoulders', equipment: 'Cable' },
    { name: 'Shoulder Press (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
    { name: 'Shoulder Press (Machine)', muscleGroup: 'Shoulders', equipment: 'Machine' },
    { name: 'Shoulder Press (Smith Machine)', muscleGroup: 'Shoulders', equipment: 'Smith Machine' },
    { name: 'Shrug (Barbell)', muscleGroup: 'Shoulders', equipment: 'Barbell' },
    { name: 'Shrug (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
    { name: 'Shrug (Machine)', muscleGroup: 'Shoulders', equipment: 'Machine' },
    { name: 'Shrug (Smith Machine)', muscleGroup: 'Shoulders', equipment: 'Smith Machine' },
    { name: 'Side Bend (Cable)', muscleGroup: 'Abs', equipment: 'Cable' },
    { name: 'Side Bend (Dumbbell)', muscleGroup: 'Abs', equipment: 'Dumbbell' },
    { name: 'Side Plank', muscleGroup: 'Abs', equipment: 'Body Weight' },
    { name: 'Single Arm Lat Pulldown (Cable)', muscleGroup: 'Back', equipment: 'Cable' },
    { name: 'Single Arm Tricep Extension (Cable)', muscleGroup: 'Arms', equipment: 'Cable' },
    { name: 'Sit-Up', muscleGroup: 'Abs', equipment: 'Body Weight' },
    { name: 'Skullcrusher (Barbell)', muscleGroup: 'Arms', equipment: 'Barbell' },
    { name: 'Skullcrusher (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell' },
    { name: 'Snatch (Barbell)', muscleGroup: 'Full Body', equipment: 'Barbell' },
    { name: 'Snatch Pull (Barbell)', muscleGroup: 'Back', equipment: 'Barbell' },
    { name: 'Squat', muscleGroup: 'Legs', equipment: 'Body Weight' },
    { name: 'Squat (Band)', muscleGroup: 'Legs', equipment: 'Band' },
    { name: 'Squat (Dumbbell)', muscleGroup: 'Legs', equipment: 'Dumbbell' },
    { name: 'Squat (Machine)', muscleGroup: 'Legs', equipment: 'Machine' },
    { name: 'Squat (Smith Machine)', muscleGroup: 'Legs', equipment: 'Smith Machine' },
    { name: 'Stability Ball Crunch', muscleGroup: 'Abs', equipment: 'Stability Ball' },
    { name: 'Standing Calf Raise (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell' },
    { name: 'Standing Calf Raise (Machine)', muscleGroup: 'Legs', equipment: 'Machine' },
    { name: 'Standing Face Pull (Cable)', muscleGroup: 'Back', equipment: 'Cable' },
    { name: 'Standing Preacher Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell' },
    { name: 'Standing Tricep Extension (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell' },
    { name: 'Stiff-Leg Deadlift (Band)', muscleGroup: 'Legs', equipment: 'Band' },
    { name: 'Stiff-Leg Deadlift (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell' },
    { name: 'Stiff-Leg Deadlift (Dumbbell)', muscleGroup: 'Legs', equipment: 'Dumbbell' },
    { name: 'Sumo Deadlift (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell' },
    { name: 'Sumo Deadlift High Pull', muscleGroup: 'Legs', equipment: 'Barbell' },
    { name: 'Thruster (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell' },
    { name: 'Thruster (Dumbbell)', muscleGroup: 'Legs', equipment: 'Dumbbell' },
    { name: 'Torso Rotation (Machine)', muscleGroup: 'Abs', equipment: 'Machine' },
    { name: 'Tricep Extension (Machine)', muscleGroup: 'Arms', equipment: 'Machine' },
    { name: 'Twist (Cable)', muscleGroup: 'Abs', equipment: 'Cable' },
    { name: 'Upright Row (Barbell)', muscleGroup: 'Shoulders', equipment: 'Barbell' },
    { name: 'Upright Row (Cable)', muscleGroup: 'Shoulders', equipment: 'Cable' },
    { name: 'Upright Row (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell' },
    { name: 'V-Up', muscleGroup: 'Abs', equipment: 'Body Weight' },
    { name: 'Wide Bench Press (Barbell)', muscleGroup: 'Chest', equipment: 'Barbell' },
    { name: 'Wide Pull-Up', muscleGroup: 'Back', equipment: 'Body Weight' },
    { name: 'Wrist Roller', muscleGroup: 'Arms', equipment: 'Accessory' },
    { name: 'Zercher Squat (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell' },
];
