export const exercises = [
    { name: '45-Degree Leg Press (Machine)', muscleGroup: 'Legs', equipment: 'Machine', weighted: 'standard' },
    { name: 'T-Bar Row (Machine)', muscleGroup: 'Back', equipment: 'Machine', weighted: 'standard' },
    { name: 'Ab Wheel Rollout', muscleGroup: 'Abs', equipment: 'Ab Wheel', weighted: 'weighted bodyweight' },
    { name: 'Arnold Press (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Around the World (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Assisted Pull-Up (Band)', muscleGroup: 'Back', equipment: 'Band', weighted: 'assisted bodyweight' },
    { name: 'Back Extension', muscleGroup: 'Back', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Back Extension (Machine)', muscleGroup: 'Back', equipment: 'Machine', weighted: 'standard' },
    { name: 'Back Squat (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Ball Slam', muscleGroup: 'Abs', equipment: 'Medicine Ball', weighted: 'standard' },
    { name: 'Bench Dip', muscleGroup: 'Arms', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Bench Press (Barbell)', muscleGroup: 'Chest', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Bench Press (Cable)', muscleGroup: 'Chest', equipment: 'Cable', weighted: 'standard' },
    { name: 'Bench Press (Dumbbell)', muscleGroup: 'Chest', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Bench Press (Smith Machine)', muscleGroup: 'Chest', equipment: 'Smith Machine', weighted: 'standard' },
    { name: 'Bench Split Squat', muscleGroup: 'Legs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Bench Squat (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Bent-Over Row (Band)', muscleGroup: 'Back', equipment: 'Band', weighted: 'standard' },
    { name: 'Bent-Over Row (Barbell)', muscleGroup: 'Back', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Bent-Over Row (Dumbbell)', muscleGroup: 'Back', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Bicep Curl (Barbell)', muscleGroup: 'Arms', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Bicep Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Bicep Curl (Machine)', muscleGroup: 'Arms', equipment: 'Machine', weighted: 'standard' },
    { name: 'Biceps Curl (Cable)', muscleGroup: 'Arms', equipment: 'Cable', weighted: 'standard' },
    { name: 'Bicycle Crunch', muscleGroup: 'Abs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Box Jump', muscleGroup: 'Legs', equipment: 'Plyo Box', weighted: 'weighted bodyweight' },
    { name: 'Burpee', muscleGroup: 'Full Body', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Calf Raise (Dumbbell)', muscleGroup: 'Legs', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Calf Raise on 45-Degree Leg Press (Machine)', muscleGroup: 'Legs', equipment: 'Machine', weighted: 'standard' },
    { name: 'Calf Raise on Leg Press (Machine)', muscleGroup: 'Legs', equipment: 'Machine', weighted: 'standard' },
    { name: 'Calf Raise (Smith Machine)', muscleGroup: 'Legs', equipment: 'Smith Machine', weighted: 'standard' },
    { name: 'Chest Dip', muscleGroup: 'Chest', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Chest Dip (Assisted)', muscleGroup: 'Chest', equipment: 'Machine', weighted: 'assisted bodyweight' },
    { name: 'Chest Fly (Cable)', muscleGroup: 'Chest', equipment: 'Cable', weighted: 'standard' },
    { name: 'Chest Fly (Dumbbell)', muscleGroup: 'Chest', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Chest Fly (Machine)', muscleGroup: 'Chest', equipment: 'Machine', weighted: 'standard' },
    { name: 'Chest Press (Machine)', muscleGroup: 'Chest', equipment: 'Machine', weighted: 'standard' },
    { name: 'Chin-Up', muscleGroup: 'Back', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Chin-Up (Assisted)', muscleGroup: 'Back', equipment: 'Machine', weighted: 'assisted bodyweight' },
    { name: 'Clean and Jerk (Barbell)', muscleGroup: 'Full Body', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Clean High Pull (Barbell)', muscleGroup: 'Back', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Close-Grip Bench Press (Barbell)', muscleGroup: 'Arms', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Concentration Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Cross-Body Crunch', muscleGroup: 'Abs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Crunch', muscleGroup: 'Abs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Crunch (Cable)', muscleGroup: 'Abs', equipment: 'Cable', weighted: 'standard' },
    { name: 'Deadlift (Band)', muscleGroup: 'Legs', equipment: 'Band', weighted: 'standard' },
    { name: 'Deadlift (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Deadlift (Dumbbell)', muscleGroup: 'Legs', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Deadlift from Deficit (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Deadlift (Smith Machine)', muscleGroup: 'Legs', equipment: 'Smith Machine', weighted: 'standard' },
    { name: 'Deadlift (Trap Bar)', muscleGroup: 'Legs', equipment: 'Trap Bar', weighted: 'standard' },
    { name: 'Decline Bench Press (Barbell)', muscleGroup: 'Chest', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Decline Bench Press (Dumbbell)', muscleGroup: 'Chest', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Decline Bench (Smith Machine)', muscleGroup: 'Chest', equipment: 'Smith Machine', weighted: 'standard' },
    { name: 'Decline Crunch', muscleGroup: 'Abs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Decline Sit-Up', muscleGroup: 'Abs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Floor Press (Barbell)', muscleGroup: 'Chest', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Front Raise', muscleGroup: 'Shoulders', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Front Raise (Band)', muscleGroup: 'Shoulders', equipment: 'Band', weighted: 'standard' },
    { name: 'Front Raise (Barbell)', muscleGroup: 'Shoulders', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Front Raise (Cable)', muscleGroup: 'Shoulders', equipment: 'Cable', weighted: 'standard' },
    { name: 'Front Raise (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Glute-Ham Raise', muscleGroup: 'Legs', equipment: 'GHD', weighted: 'weighted bodyweight' },
    { name: 'Glute Kickback (Machine)', muscleGroup: 'Legs', equipment: 'Machine', weighted: 'standard' },
    { name: 'Goblet Squat (Dumbbell)', muscleGroup: 'Legs', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Good Morning (Barbell)', muscleGroup: 'Back', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Hack Squat (Sled Machine)', muscleGroup: 'Legs', equipment: 'Sled Machine', weighted: 'standard' },
    { name: 'Hammer Curl (Band)', muscleGroup: 'Arms', equipment: 'Band', weighted: 'standard' },
    { name: 'Hammer Curl (Cable)', muscleGroup: 'Arms', equipment: 'Cable', weighted: 'standard' },
    { name: 'Hammer Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Handstand Push-Up', muscleGroup: 'Shoulders', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Hang Clean (Barbell)', muscleGroup: 'Full Body', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Hang Snatch (Barbell)', muscleGroup: 'Full Body', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Hanging Knees to Elbows', muscleGroup: 'Abs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Hanging Leg Raise', muscleGroup: 'Abs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Hanging Toes to Bar', muscleGroup: 'Abs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Hip Adduction (Machine)', muscleGroup: 'Legs', equipment: 'Machine', weighted: 'standard' },
    { name: 'Hip Thrust (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Incline Bench (Barbell)', muscleGroup: 'Chest', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Incline Bench Press (Cable)', muscleGroup: 'Chest', equipment: 'Cable', weighted: 'standard' },
    { name: 'Incline Bench Press (Dumbbell)', muscleGroup: 'Chest', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Incline Bench (Smith Machine)', muscleGroup: 'Chest', equipment: 'Smith Machine', weighted: 'standard' },
    { name: 'Incline Bicep Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Incline Chest Press (Machine)', muscleGroup: 'Chest', equipment: 'Machine', weighted: 'standard' },
    { name: 'Incline Fly (Dumbbell)', muscleGroup: 'Chest', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Incline Row (Barbell)', muscleGroup: 'Back', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Incline Row (Dumbbell)', muscleGroup: 'Back', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Inverted Row', muscleGroup: 'Back', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Jerk (Barbell)', muscleGroup: 'Full Body', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Jump Shrug (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Jump Squat', muscleGroup: 'Legs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Kettlebell Swing', muscleGroup: 'Full Body', equipment: 'Kettlebell', weighted: 'standard' },
    { name: 'Kettlebell Turkish Get-Up', muscleGroup: 'Full Body', equipment: 'Kettlebell', weighted: 'standard' },
    { name: 'Knee Push-Up', muscleGroup: 'Chest', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Lat Pulldown (Cable)', muscleGroup: 'Back', equipment: 'Cable', weighted: 'standard' },
    { name: 'Lat Pulldown (Machine)', muscleGroup: 'Back', equipment: 'Machine', weighted: 'standard' },
    { name: 'Lateral Raise (Band)', muscleGroup: 'Shoulders', equipment: 'Band', weighted: 'standard' },
    { name: 'Lateral Raise (Cable)', muscleGroup: 'Shoulders', equipment: 'Cable', weighted: 'standard' },
    { name: 'Lateral Raise (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Lateral Raise (Machine)', muscleGroup: 'Shoulders', equipment: 'Machine', weighted: 'standard' },
    { name: 'Leg Curl (Machine)', muscleGroup: 'Legs', equipment: 'Machine', weighted: 'standard' },
    { name: 'Leg Extension (Machine)', muscleGroup: 'Legs', equipment: 'Machine', weighted: 'standard' },
    { name: 'Leg Press (Machine)', muscleGroup: 'Legs', equipment: 'Machine', weighted: 'standard' },
    { name: 'Leg Raise', muscleGroup: 'Abs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Leg Raise (Captain\'s Chair)', muscleGroup: 'Abs', equipment: 'Captain\'s Chair', weighted: 'weighted bodyweight' },
    { name: 'Lunge', muscleGroup: 'Legs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Lunge (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Lunge (Dumbbell)', muscleGroup: 'Legs', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Lying Knee Raise', muscleGroup: 'Abs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Lying Leg Curl (Machine)', muscleGroup: 'Legs', equipment: 'Machine', weighted: 'standard' },
    { name: 'Muscle-Up', muscleGroup: 'Full Body', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Oblique Crunch', muscleGroup: 'Abs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'One-Arm Curl (Cable)', muscleGroup: 'Arms', equipment: 'Cable', weighted: 'standard' },
    { name: 'Overhead Squat (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Overhead Tricep Extension (Barbell)', muscleGroup: 'Arms', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Overhead Tricep Extension (Cable)', muscleGroup: 'Arms', equipment: 'Cable', weighted: 'standard' },
    { name: 'Pec Deck (Machine)', muscleGroup: 'Chest', equipment: 'Machine', weighted: 'standard' },
    { name: 'Pendlay Row (Barbell)', muscleGroup: 'Back', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Pistol Squat', muscleGroup: 'Legs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Power Clean', muscleGroup: 'Full Body', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Preacher Curl (Barbell)', muscleGroup: 'Arms', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Preacher Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Preacher Curl (Machine)', muscleGroup: 'Arms', equipment: 'Machine', weighted: 'standard' },
    { name: 'Press Under (Barbell)', muscleGroup: 'Shoulders', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Pull-Through (Cable)', muscleGroup: 'Back', equipment: 'Cable', weighted: 'standard' },
    { name: 'Pull-Up', muscleGroup: 'Back', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Pull-Up (Assisted)', muscleGroup: 'Back', equipment: 'Machine', weighted: 'assisted bodyweight' },
    { name: 'Pullover (Dumbbell)', muscleGroup: 'Chest', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Pullover (Machine)', muscleGroup: 'Chest', equipment: 'Machine', weighted: 'standard' },
    { name: 'Push-Up', muscleGroup: 'Chest', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Push-Up (Band)', muscleGroup: 'Chest', equipment: 'Band', weighted: 'weighted bodyweight' },
    { name: 'Pushdown (Cable)', muscleGroup: 'Arms', equipment: 'Cable', weighted: 'standard' },
    { name: 'Rack Pull (Barbell)', muscleGroup: 'Back', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Raise (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Rear Fly (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Reverse Concentration Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Reverse Crunch', muscleGroup: 'Abs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Reverse Curl (Barbell)', muscleGroup: 'Arms', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Reverse Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Reverse Fly (Cable)', muscleGroup: 'Shoulders', equipment: 'Cable', weighted: 'standard' },
    { name: 'Reverse Fly (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Reverse Fly (Machine)', muscleGroup: 'Shoulders', equipment: 'Machine', weighted: 'standard' },
    { name: 'Reverse Grip Bent-Over Row (Barbell)', muscleGroup: 'Back', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Reverse Preacher Curl (Barbell)', muscleGroup: 'Arms', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Reverse Preacher Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Reverse Wrist Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Romanian Deadlift (Dumbbell)', muscleGroup: 'Legs', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Russian Twist', muscleGroup: 'Abs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Seated Calf Press (Machine)', muscleGroup: 'Legs', equipment: 'Machine', weighted: 'standard' },
    { name: 'Seated Calf Raise (Machine)', muscleGroup: 'Legs', equipment: 'Machine', weighted: 'standard' },
    { name: 'Seated Crunch (Machine)', muscleGroup: 'Abs', equipment: 'Machine', weighted: 'standard' },
    { name: 'Seated Row (Cable)', muscleGroup: 'Back', equipment: 'Cable', weighted: 'standard' },
    { name: 'Seated Row (Machine)', muscleGroup: 'Back', equipment: 'Machine', weighted: 'standard' },
    { name: 'Seated Shoulder Press (Barbell)', muscleGroup: 'Shoulders', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Seated Single Leg Press (Machine)', muscleGroup: 'Legs', equipment: 'Machine', weighted: 'standard' },
    { name: 'Seated Wrist Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Shoulder Press (Barbell)', muscleGroup: 'Shoulders', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Shoulder Press (Cable)', muscleGroup: 'Shoulders', equipment: 'Cable', weighted: 'standard' },
    { name: 'Shoulder Press (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Shoulder Press (Machine)', muscleGroup: 'Shoulders', equipment: 'Machine', weighted: 'standard' },
    { name: 'Shoulder Press (Smith Machine)', muscleGroup: 'Shoulders', equipment: 'Smith Machine', weighted: 'standard' },
    { name: 'Shrug (Barbell)', muscleGroup: 'Shoulders', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Shrug (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Shrug (Machine)', muscleGroup: 'Shoulders', equipment: 'Machine', weighted: 'standard' },
    { name: 'Shrug (Smith Machine)', muscleGroup: 'Shoulders', equipment: 'Smith Machine', weighted: 'standard' },
    { name: 'Side Bend (Cable)', muscleGroup: 'Abs', equipment: 'Cable', weighted: 'standard' },
    { name: 'Side Bend (Dumbbell)', muscleGroup: 'Abs', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Single Arm Lat Pulldown (Cable)', muscleGroup: 'Back', equipment: 'Cable', weighted: 'standard' },
    { name: 'Single Arm Tricep Extension (Cable)', muscleGroup: 'Arms', equipment: 'Cable', weighted: 'standard' },
    { name: 'Sit-Up', muscleGroup: 'Abs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Skullcrusher (Barbell)', muscleGroup: 'Arms', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Skullcrusher (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Snatch (Barbell)', muscleGroup: 'Full Body', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Snatch Pull (Barbell)', muscleGroup: 'Back', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Squat', muscleGroup: 'Legs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Squat (Band)', muscleGroup: 'Legs', equipment: 'Band', weighted: 'standard' },
    { name: 'Squat (Dumbbell)', muscleGroup: 'Legs', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Squat (Machine)', muscleGroup: 'Legs', equipment: 'Machine', weighted: 'standard' },
    { name: 'Squat (Smith Machine)', muscleGroup: 'Legs', equipment: 'Smith Machine', weighted: 'standard' },
    { name: 'Stability Ball Crunch', muscleGroup: 'Abs', equipment: 'Stability Ball', weighted: 'weighted bodyweight' },
    { name: 'Standing Calf Raise (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Standing Calf Raise (Machine)', muscleGroup: 'Legs', equipment: 'Machine', weighted: 'standard' },
    { name: 'Standing Face Pull (Cable)', muscleGroup: 'Back', equipment: 'Cable', weighted: 'standard' },
    { name: 'Standing Preacher Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Standing Tricep Extension (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Stiff-Leg Deadlift (Band)', muscleGroup: 'Legs', equipment: 'Band', weighted: 'standard' },
    { name: 'Stiff-Leg Deadlift (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Stiff-Leg Deadlift (Dumbbell)', muscleGroup: 'Legs', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Sumo Deadlift (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Sumo Deadlift High Pull', muscleGroup: 'Legs', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Thruster (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Thruster (Dumbbell)', muscleGroup: 'Legs', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Torso Rotation (Machine)', muscleGroup: 'Abs', equipment: 'Machine', weighted: 'standard' },
    { name: 'Tricep Extension (Machine)', muscleGroup: 'Arms', equipment: 'Machine', weighted: 'standard' },
    { name: 'Twist (Cable)', muscleGroup: 'Abs', equipment: 'Cable', weighted: 'standard' },
    { name: 'Upright Row (Barbell)', muscleGroup: 'Shoulders', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Upright Row (Cable)', muscleGroup: 'Shoulders', equipment: 'Cable', weighted: 'standard' },
    { name: 'Upright Row (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'V-Up', muscleGroup: 'Abs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Wide Bench Press (Barbell)', muscleGroup: 'Chest', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Wide Pull-Up', muscleGroup: 'Back', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Wrist Roller', muscleGroup: 'Arms', equipment: 'Accessory', weighted: 'standard' },
    { name: 'Zercher Squat (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Pallof Press (Cable)', muscleGroup: 'Abs', equipment: 'Cable', weighted: 'standard' },
    { name: 'Pallof Press (Band)', muscleGroup: 'Abs', equipment: 'Band', weighted: 'standard' },
    { name: 'Cable Woodchop', muscleGroup: 'Abs', equipment: 'Cable', weighted: 'standard' },
    { name: 'Standing Cable Crunch', muscleGroup: 'Abs', equipment: 'Cable', weighted: 'standard' },
    { name: 'Hanging Windshield Wipers', muscleGroup: 'Abs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Hollow Hold', muscleGroup: 'Abs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Dragon Flag', muscleGroup: 'Abs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Side Plank Hip Lift', muscleGroup: 'Abs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Meadows Row (Barbell)', muscleGroup: 'Back', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Chest Supported Row (Dumbbell)', muscleGroup: 'Back', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Chest Supported Row (Barbell)', muscleGroup: 'Back', equipment: 'Barbell', weighted: 'standard' },
    { name: 'High Row (Machine)', muscleGroup: 'Back', equipment: 'Machine', weighted: 'standard' },
    { name: 'Wide-Grip Seated Row (Cable)', muscleGroup: 'Back', equipment: 'Cable', weighted: 'standard' },
    { name: 'Narrow-Grip Seated Row (Cable)', muscleGroup: 'Back', equipment: 'Cable', weighted: 'standard' },
    { name: 'Single-Arm Standing Row (Cable)', muscleGroup: 'Back', equipment: 'Cable', weighted: 'standard' },
    { name: 'Reverse Hyperextension', muscleGroup: 'Back', equipment: 'GHD', weighted: 'standard' },
    { name: 'Landmine Deadlift (Barbell)', muscleGroup: 'Back', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Spider Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Preacher Curl (Cable)', muscleGroup: 'Arms', equipment: 'Cable', weighted: 'standard' },
    { name: 'Cross-Body Hammer Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Incline Hammer Curl (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Reverse Grip Pushdown (Cable)', muscleGroup: 'Arms', equipment: 'Cable', weighted: 'standard' },
    { name: 'Lying Cable Triceps Extension', muscleGroup: 'Arms', equipment: 'Cable', weighted: 'standard' },
    { name: 'Single-Arm Overhead Triceps Extension (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Tate Press (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Tricep Kickback (Dumbbell)', muscleGroup: 'Arms', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Tricep Kickback (Cable)', muscleGroup: 'Arms', equipment: 'Cable', weighted: 'standard' },
    { name: 'Landmine Press (Barbell)', muscleGroup: 'Shoulders', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Half-Kneeling Landmine Press (Barbell)', muscleGroup: 'Shoulders', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Z Press (Barbell)', muscleGroup: 'Shoulders', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Dumbbell Raise (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Y-Raise (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Rear Delt Row (Dumbbell)', muscleGroup: 'Shoulders', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Band Pull-Apart', muscleGroup: 'Shoulders', equipment: 'Band', weighted: 'standard' },
    { name: 'Incline Push-Up', muscleGroup: 'Chest', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Decline Push-Up', muscleGroup: 'Chest', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Archer Push-Up', muscleGroup: 'Chest', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Dumbbell Squeeze Press', muscleGroup: 'Chest', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Dumbbell Floor Press', muscleGroup: 'Chest', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Kneeling High-to-Low Cable Fly', muscleGroup: 'Chest', equipment: 'Cable', weighted: 'standard' },
    { name: 'Low-to-High Cable Fly', muscleGroup: 'Chest', equipment: 'Cable', weighted: 'standard' },
    { name: 'Close-Grip Push-Up', muscleGroup: 'Chest', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Bulgarian Split Squat (Dumbbell)', muscleGroup: 'Legs', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Bulgarian Split Squat (Body Weight)', muscleGroup: 'Legs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Curtsy Lunge (Dumbbell)', muscleGroup: 'Legs', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Step-Up (Dumbbell)', muscleGroup: 'Legs', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'Step-Up (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Box Squat (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Hip Thrust (Dumbbell)', muscleGroup: 'Legs', equipment: 'Dumbbell', weighted: 'standard' },
    { name: 'One-leg Hip Thrust (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Hip Abduction (Machine)', muscleGroup: 'Legs', equipment: 'Machine', weighted: 'standard' },
    { name: 'Nordic Hamstring Curl (Body Weight)', muscleGroup: 'Legs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Nordic Hamstring Curl (Assisted)', muscleGroup: 'Legs', equipment: 'Body Weight', weighted: 'assisted bodyweight' },
    { name: 'Sissy Squat (Body Weight)', muscleGroup: 'Legs', equipment: 'Body Weight', weighted: 'weighted bodyweight' },
    { name: 'Landmine Squat (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell', weighted: 'standard' },
    { name: 'Landmine Reverse Lunge (Barbell)', muscleGroup: 'Legs', equipment: 'Barbell', weighted: 'standard' },
];
